version: '3'

services:
  web:
    build: ./docker/web
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"

  db:
    image: mysql:latest 
    volumes:
      - db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_docker
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db: